GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY4MjY4NzUsImV4cCI6MTY2NjgzMDQ3NSwiYXVkIjoiNjM1OWI1ZjhmZjMzMjE4ZTc2NTQ3ZmVhIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.wqqDQadgl5b1PieetMqz4IcFzRoymEN9ResDKnmUT7A
